name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up secret file
      run: |
        echo ${{secrets.test}} | sed 's/./& /g' | tr -d ' '
